config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  get 'search' => 'search#index' , as: :search
  post 'search/result' => 'search#search_result' , as: :search_result
  devise_for :users

  root 'static_pages#home'
  get 'index' => 'static_pages#index' 
  get '/recipes' => 'static_pages#index' ,as: :index_page
  get '/recipes/:id' => 'static_pages#show', as: :individual_recipe
  post '/recipes/var' => 'static_pages#var', as: :var
  get 'recipie/new' => 'recipie#new' , as: :recipie_new
  post 'recipie/create' => 'recipie#create' ,as: :recipie_create
  get 'recipie/index' => 'recipie#index' ,as: :recipie_index
  get 'recipie/edit' => 'recipie#edit' , as: :recipie_edit
  patch 'recipie/update' => 'recipie#update' , as: :recipie_update
  delete 'recipie/delete/:id' => 'recipie#destroy' , as: :recipie_destroy

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	belongs_to :recipe
end

app/models/query.rb
class Query < ActiveRecord::Base
end

app/models/rating.rb
class Rating < ActiveRecord::Base
	belongs_to :user
	belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	belongs_to :user
	has_many :ingredients , dependent: :destroy
	accepts_nested_attributes_for :ingredients,allow_destroy: true
	has_many :ratings

	def avg_rating
		avg_score = 0
		if self.ratings.count != 0
			self.ratings.each do |rating|
				avg_score = avg_score + rating.score
			end
			avg_score = avg_score/self.ratings.count
		else
			avg_score = 0
		end
		avg_score
	end

	def get_user
		user = User.find(self.user_id)
		user
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes , dependent: :destroy
  has_many :ratings , dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipie_controller.rb
class RecipieController < ApplicationController
	before_action :authenticate_user!

	def new
		@recipe = Recipe.new
		@recipe.ingredients.build
	end

	def create
		@recipe = Recipe.new(recipe_params)
		@recipe.user_id = current_user.id
		if recipe_valid params		
			if @recipe.save
				flash[:notice]= "saved"
			else
				flash[:notice] = "not saved"
			end
		else
			flash[:notice] = "fields missing"
		end
		redirect_to recipie_index_path
	end


	def edit
		puts "++++++++++++++++"
		puts params
		@recipe = Recipe.find(params[:r_id])
		@id = @recipe.id
	end

	def update
		puts "++++++++++===============++++++++"
		puts "update"
		puts params
		puts params[:recipe][:title]
		@recipe = Recipe.find(params[:id])
		if recipe_valid params
			if @recipe.update(recipe_params)
	    		redirect_to recipie_index_path
	    		flash[:notice]= "saved"
	    	else
	    		flash[:notice]= "not saved"
	    	end
  		else
  			flash[:notice] = "fields missing"
    		render 'edit'
  		end
	end

	def destroy
	@recipie = Recipe.find(params[:id])
	if @recipie.destroy
		flash[:notice] = "deleted"
	end
		respond_to do |format|
    		format.html {}
    		format.js {}
    	end
	end

	def index
		@user = current_user
		@recipes = current_user.recipes
	end

private
	def recipe_params
      params.require(:recipe).permit(:title, :description , ingredients_attributes: [:id , :ingredient_name ,:_destroy])
    end
    def recipe_valid params
    	if params[:recipe][:title].blank? || params[:recipe][:description].blank?
    		false
    	else
    		true
    	end
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  	@query = Query.new
  end

  def search_result
  	puts params
  	if params[:query].blank?
  		@query = params[:querys] 
  	else
  		@query = params[:query][:title]
  	end
  	@page = params[:page].to_i || 1
  	@results = GoogleCustomSearchApi.search(@query , page: @page)
  	puts @results.items.first
  	puts '++++++++++++++++++++++++++++++++'
  	puts @results.items.first.pagemap.cse_thumbnail.first.src
  end
  def searchs
  end

end
  	# @results = GoogleCustomSearchApi.search("poker")

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
	def index
		respond_to do |format|
			@all = Recipe.all.order(:created_at)
			puts "+++++++++++===========+++++++"
			puts params
    		format.html{}
    		format.js{
    			get_ratings params
    			@avg_rating = Recipe.find(params[:r_id]).avg_rating

    		}
    	end
	end
	def show
		respond_to do |format|
    		format.html {
				@recipe = Recipe.find(params[:id])		
    		}
    		format.js {
    			get_ratings params
    			flash[:alert] = "yeah baby"
    		}
    	end
	end
	def var
		@rating = Rating.new
		puts "+===============+++++++++++++++====+++++==="
		puts params
	end

	private

	def  get_ratings params
		puts "+++++++++++++"
		puts params
		puts "-------------"
		rating = Rating.find_by(recipe_id: params[:r_id], user_id: current_user.id)||Rating.new(recipe_id: params[:r_id], user_id: current_user.id)
    	rating.score = params[:rating][:score]
    	puts rating
    	if rating.save
    		flash[:notice] = "Thank you for rating"
    		@var = "Thank you for rating"
    	else
    		flash[:notice] = "Ooops something went wrong"
    		@var = "did not work"
    	end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipie_helper.rb
module RecipieHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeMaker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default navbar-modi" style="background-color: black;" >
<% if user_signed_in? %>
  <ul class = "h-list">
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  </li>
  <li>
  <%= link_to('recipes', index_page_path) %>        
  </li>
  <li>
  <%= link_to('your recipes', recipie_index_path) %>        
  </li>
  </ul>
<% else %>
  <ul class = "h-list">
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
  <li>
  <%= link_to('Sign Up', new_user_registration_path)  %>  
  </li>
 </ul>
<% end %>
</div>
<%= yield %>

</body>
</html>

app/views/recipie/_ingredient_fields.html.slim
.nested-fields
	= f.input :ingredient_name
	=link_to_remove_association "remove ingredient", f

app/views/recipie/destroy.js.erb
location.reload()

app/views/recipie/edit.html.slim
.text-center
	.all-forms
		= simple_form_for @recipe ,url: recipie_update_path(id: @recipe.id) ,method: "patch" do |f|
			=  f.input :title
		   	=  f.input :description
		   	= f.simple_fields_for :ingredients do |ingredient|
		      = render 'ingredient_fields', f: ingredient
		    .links
		      = link_to_add_association 'add ingredient', f, :ingredients
		   	= f.button :submit

app/views/recipie/index.html.slim
- if flash[:notice] 
    = flash[:notice]
.text-center
	br 
	h1 
		| hello 
		= @user.name || ""
	br
	h3
		| Number of recipes submitted: 
		= @user.recipes.count
	br
	hr
	hr
- if !@recipes.blank?
	table.all-tables
		-@recipes.each do |a|
			br
			tr
				td
					|Recipes Name: 
					= a.title
				td
					| Recipe Description	
					= a.description
				td style="display: inline"
					= link_to"edit", recipie_edit_path(r_id: a.id) ,class:'btn btn-default'

					/ = link_to"edit", recipie_edit_path(:recipe =>{id: a.id}) 
				td.del-button = link_to 'delete',recipie_destroy_path(a) , method: :delete , data: {confirm: "are you sure"} ,class:'btn btn-default',remote: true ,style: "display:inline"
.text-center	
	= link_to 'create a new recipe',recipie_new_path

app/views/recipie/new.html.slim
.text-center
	.all-forms
		= simple_form_for @recipe ,url: recipie_create_url do |f|
			=  f.input :title ,required: true
			=  f.input :description, required: true
			= f.simple_fields_for :ingredients do |ingredient|
				.ingredient_fields style="width:"
					= render 'ingredient_fields', f: ingredient
					= link_to_add_association 'add ingredients', f, :ingredients
			= f.button :submit

app/views/search/index.html.slim
h1 Search#index
p Find me in app/views/search/index.html.slim
= simple_form_for @query , url: search_result_url  do |f|
	= f.input :title  , label: false
	= f.button :submit ,"submit"
= @results

app/views/search/search_result.html.slim
ol
	- @results.items.each do |result|
		li style="color: black; background-color: blue;"
			- if result['pagemap'] && result['pagemap']['cse_thumbnail'] && img = result.pagemap.cse_thumbnail.first
				= image_tag(result.pagemap.cse_thumbnail.first.src , :style=>"height:30px;width:50px;")
			= link_to result.title,result.formattedUrl
			br
			= result.snippet
			br
			hr

.col-md-12
	.var
		- page = @page	
		- page = page + 1
		= page		
		= button_to "for more results" , search_result_url, params: {page: page, querys: @query} 
	.var1
		- page = @page	
		- page = page - 1
		= page
		= button_to "previous results" , search_result_url, params: {page: page, querys: @query} unless page <= 0

	

app/views/search/search_result.js.erb
var results = "<%=@results%>";
console.log("++++++++++"); 
console.log(results);

app/views/static_pages/_recipe_rating.html.slim
- @a = Rating.find_by(user_id: current_user.id , recipe_id: recipe.id)|| Rating.new(user_id: current_user.id , recipe_id: recipe.id)
= simple_form_for @a , url: index_page_path(r_id: recipe.id) , method: :get, remote: true do |f|
	= f.input :score, collection: 1..10
	=f.button :submit

app/views/static_pages/_recipe_rating2.html.slim
- @a = Rating.find_by(user_id: current_user.id , recipe_id: recipe.id)|| Rating.new(user_id: current_user.id , recipe_id: recipe.id)
= simple_form_for @a , url: individual_recipe_path(r_id: recipe.id) , method: :get, remote: true do |f|
	= f.input :score, collection: 1..10 , input_html: {class: 'rating'}
	=f.button :submit

app/views/static_pages/home.html.slim
h1 this is the home page nigga

app/views/static_pages/index.html.slim
.text-center.flash-message style ="height: 20px;width: 400px"
	-if flash[:message]
		|flash message
-@all.each do |recipe|
	br
	.recipe-top.text-center
		.recipe-image
			h1.recipe-title.text-center.t-place-down style="padding 5px"
				= recipe.title
			br
			.col-md-12
				.col-md-8.text-right
					|by
				.col-md-4
					h5
						= recipe.get_user.name
			hr
	.col-md-12
		h2.recipe-descp.text-left.col-md-8
			| Description:
	.recipe-description.text-center style="padding 50x; font-size: 25px"
		= recipe.description
	br
	hr
	.recipe-avg-rating.col-md-6.text-center style="border-right: thin ; border-color: rgb(238,238,238)"
		|Average user's rating
		br
		.recipe-avg
			= recipe.avg_rating
		| /10
	.recipe-individual-rating.col-md-6.text-center
		= render(partial:'recipe_rating' ,locals: {recipe: recipe})
	br
	br
	br
	.button.text-center
		.btn.btn-primary  
			= link_to "show more" , individual_recipe_path(recipe) , class: "button-text"
	

app/views/static_pages/index.js.erb
var variable = "<%=@var%>";
var avg_rating = "<%=@avg_rating%>";
console.log(variable);
console.log('works');
console.log(avg_rating);


$('.flash-message').html(variable);
$('.recipe-avg').text(avg_rating);

app/views/static_pages/show.html.slim
.flash-message
	-if flash[:notice]
		= flash[:notice]
	br
	- if flash[:alert]
		= flash[:alert]
.recipe-top
	.text-center
		h1
			= @recipe.title
		br
	.col-md-12
		.col-md-8.text-right
			|by
		.col-md-4
			h5
				= @recipe.get_user.name
	hr
.col-md-12.show-container style="padding: 50px" 
	h2.description-title.text-left
		| Description
	.description.text-center
		= @recipe.description
	br
	.col-md-4 style="border-right: solid"
		h3.text-left.ingredients-title
			| Ingredients
		.text-center.ingredients
		-@recipe.ingredients.each do |ing|
			= ing.ingredient_name
			br
	.col-md-8
		h3.text-left.steps-title
			| Steps
		.text-center.steps
.col-md-12-rate
		= render(partial:'recipe_rating2' ,locals: {recipe: @recipe})

app/views/static_pages/show.js.erb
$('.recipe-top').hide();
var variable = "<%=@var%>";
console.log(variable);
console.log('works');

$('.flash-message').html(variable);

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>